services:
  kafka:
    image: confluentinc/cp-kafka:8.1.0
    restart: unless-stopped
    environment:
      KAFKA_KRAFT_MODE: "true" # This enables KRaft mode in Kafka
      KAFKA_PROCESS_ROLES: broker,controller # Kafka acts as both broker and controller.
      KAFKA_NODE_ID: 1 # A unique ID for this Kafka instance.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093 # Defines the controller voters.
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LOG_DIRS: /var/lib/kafka/data # Where Kafka stores its logs.
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Kafka will automatically create topics if needed.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Since weâ€™re running one broker, one replica is enough.
      KAFKA_LOG_RETENTION_HOURS: 168 # Keep logs for 7 days.
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # No delay for consumer rebalancing.
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk" # A unique ID for the Kafka cluster.
    volumes:
      - kafka-broker-data:/var/lib/kafka/data
    healthcheck:
      test:
        - "CMD"
        - "kafka-topics"
        - "--bootstrap-server"
        - "localhost:9092"
        - "--list"
      interval: 30s
      timeout: 5s
      start_period: 120s
      retries: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
    volumes:
      - kafka-ui-data:/kafka

  opa:
    image: openpolicyagent/opa
    restart: unless-stopped
    command: run --server --log-level debug --addr 0.0.0.0:8181 /fed_mgr
    volumes:
      - ./opa-data:/fed_mgr:ro

  db:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        - "CMD"
        - "mysqladmin"
        - "ping"
        - "-h"
        - "127.0.0.1"
        - "-uroot"
        - "-p${MYSQL_ROOT_PASSWORD}"
        - "--silent"
      interval: 10s
      timeout: 5s
      start_period: 120s
      retries: 3

  backend:
    image: ${FM_BACKEND_IMAGE:-indigopaas/fed-mgr:python3.12}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      opa:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_SCHEME: mysql+pymysql
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
      DB_HOST: db
      AUTHN_MODE: local
      AUTHZ_MODE: opa
      TRUSTED_IDP_LIST: '["https://iam.cloud.infn.it/"]'
      OPA_AUTHZ_URL: http://opa:8181/v1/data/fed_mgr
      KAFKA_ENABLE: true
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_TOPIC: fed-mgr-rally
      API_KEY: changeit
      LOCAL_ENCRYPTION: false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health/"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3

  rally:
    image: ${FM_RALLY_IMAGE:-indigopaas/fed-mgr-rally:python3.13}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      kafka:
        condition: service_healthy
    env_file:
      - .env
    environment:
      FED_MGR_API_URL: http://fed-mgr/api/v1/
      X_API_KEY: changeit
      KAFKA_ENABLE: true
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      KAFKA_TOPIC: fed-mgr-rally
      RALLY_ENV_FOLDER: /app/environments
      RALLY_ARGS_FOLDER: /app/args
      RALLY_REPORT_FOLDER: /app/reports
    command: sleep infinity
    volumes:
      - rally-environments:/app/environments
      - rally-args:/app/args
      - rally-reports:/app/reports

  dashboard:
    image: ${FM_DASHBOARD_IMAGE:-indigopaas/fed-mgr-dashboard}
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      start_period: 30s
    env_file:
      - .env
    environment:
      FM_OIDC_URL:
      FM_OIDC_CLIENT_ID:
      FM_OIDC_CLIENT_SECRET:
      FM_OIDC_SCOPES:
      FM_OIDC_PROVIDER_ID:
      FM_AUTH_SECRET:
      FM_ENDPOINT_URL: http://${FM_SERVER_NAME}:8080
      API_SERVER_URL: http://${FM_SERVER_NAME}:8080/api/v1
      GROUPS_SITE_ADMIN:
      GROUPS_SITE_TESTER:
      GROUPS_SLA_MANAGER:
      GROUPS_ADMIN:

  nginx:
    image: nginx:1.27-alpine
    hostname: ${FM_SERVER_NAME}
    # command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/templates
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    env_file:
      - .env
    environment:
      FM_SERVER_NAME:
    depends_on:
      dashboard:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  db-data:
  db-auth:
  kafka-broker-data:
  kafka-ui-data:
  rally-environments:
  rally-args:
  rally-reports:
